### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by jjkoehorst** [twardoch/mkdocs-combine#8]
I have used mkdocs2pandoc > Reader.pd but this was excluding "empty" sections such as 

- Practical WetLab: 
  - Week 1:
    - Tuesday:
      - ExperimentX: 'Practical/WetLab/Week1/Tuesday/ExperimentX.md'

In which I would like to also have Practical WetLab, Week1, Tuesday, ExperimentX in the PDF.

Now I was trying this program and all I get is

# Practical WetLab {: .page-title}

### Wednesday {: .page-title}

The actual content is missing?

**Comment by twardoch** [comment]
Fixed in https://github.com/twardoch/mkdocs-combine/releases/tag/0.3.1.1

**Comment by twardoch** [comment]
(At some point mkdocs started using 'unicode' filenames while this tool only expected 'str', it works now)

**Comment by chrisgb-dev** [comment]
I'm getting the same issue as @jjkoehorst. I'm on release 0.3.1.1 and get the same empty output. 

Anything else I could be doing wrong?

**Comment by snow212-cn** [comment]
I'm getting the same issue as  @jjkoehorst, @foss-scribe ! 0.3.1.1
What piece of shit **we** all could do wrong?
